sudo: required
services:
- docker
language: python
python:
- '3.6'
before_install:
- sudo rm -f /etc/boto.cfg
install:
- wget https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip
  -O browserStackLocal.zip
- unzip browserStackLocal.zip
- "./BrowserStackLocal --key $KEY --force-local &"
- sudo docker --version
- sudo docker-compose --version
jobs:
  include:
  - stage: test
    name: Load content
    script: "./csu ci load_content"
  - script: "./csu ci test_general"
    name: Run general tests
  - script: "./csu ci test_resources"
    name: Run resource tests
  - script: "./csu ci test_management"
    name: Run management tests
  - script: "./csu ci test_backwards"
    name: Run test suite backwards
    if: type = pull_request
  - script: "./csu ci test_in_browser"
    name: Run in-browser tests
  - script: "./csu ci style"
    name: Run style checker
  - script: "./csu ci docs"
    name: Build documentation
  - stage: develop deploy
    name: Deploy app to Google App Engine
    script: skip
    deploy:
    - provider: script
      script: bash ./infrastructure/dev-deploy/deploy-app.sh
      skip_cleanup: true
      on:
        branch: develop
  - script: skip
    name: Copy static files to Google Storage Bucket
    deploy:
    - provider: script
      script: bash ./infrastructure/dev-deploy/deploy-static-files.sh
      skip_cleanup: true
      on:
        branch: develop
  - script: skip
    name: Update Google Cloud Platform database
    deploy:
    - provider: script
      script: bash ./infrastructure/dev-deploy/update-database.sh
      skip_cleanup: true
      on:
        branch: develop
  - script: skip
    name: Copy resource PDFs to Google Storage Bucket - Part 1
    deploy:
    - provider: script
      script: bash ./infrastructure/dev-deploy/deploy-resources-1.sh
      skip_cleanup: true
      on:
        branch: develop
  - script: skip
    name: Copy resource PDFs to Google Storage Bucket - Part 2
    deploy:
    - provider: script
      script: bash ./infrastructure/dev-deploy/deploy-resources-2.sh
      skip_cleanup: true
      on:
        branch: develop
  - script: skip
    name: Copy resource PDFs to Google Storage Bucket - Part 3
    deploy:
    - provider: script
      script: bash ./infrastructure/dev-deploy/deploy-resources-3.sh
      skip_cleanup: true
      on:
        branch: develop
  - script: skip
    name: Copy resource PDFs to Google Storage Bucket - Part 4
    deploy:
    - provider: script
      script: bash ./infrastructure/dev-deploy/deploy-resources-4.sh
      skip_cleanup: true
      on:
        branch: develop
  - script: skip
    name: Copy resource PDFs to Google Storage Bucket - Part 5
    deploy:
    - provider: script
      script: bash ./infrastructure/dev-deploy/deploy-resources-5.sh
      skip_cleanup: true
      on:
        branch: develop
  - stage: production deploy
    script: skip
    name: Deploy app to Google App Engine
    deploy:
    - provider: script
      script: bash ./infrastructure/prod-deploy/deploy-app.sh
      skip_cleanup: true
      on:
        branch: master
  - script: skip
    name: Copy static files to Google Storage Bucket
    deploy:
    - provider: script
      script: bash ./infrastructure/prod-deploy/deploy-static-files.sh
      skip_cleanup: true
      on:
        branch: master
  - script: skip
    name: Update Google Cloud Platform database
    deploy:
    - provider: script
      script: bash ./infrastructure/prod-deploy/update-database.sh
      skip_cleanup: true
      on:
        branch: master
  - script: skip
    name: Copy resource PDFs to Google Storage Bucket - Part 1
    deploy:
    - provider: script
      script: bash ./infrastructure/prod-deploy/deploy-resources-1.sh
      skip_cleanup: true
      on:
        branch: master
  - script: skip
    name: Copy resource PDFs to Google Storage Bucket - Part 2
    deploy:
    - provider: script
      script: bash ./infrastructure/prod-deploy/deploy-resources-2.sh
      skip_cleanup: true
      on:
        branch: master
  - script: skip
    name: Copy resource PDFs to Google Storage Bucket - Part 3
    deploy:
    - provider: script
      script: bash ./infrastructure/prod-deploy/deploy-resources-3.sh
      skip_cleanup: true
      on:
        branch: master
  - script: skip
    name: Copy resource PDFs to Google Storage Bucket - Part 4
    deploy:
    - provider: script
      script: bash ./infrastructure/prod-deploy/deploy-resources-4.sh
      skip_cleanup: true
      on:
        branch: master
  - script: skip
    name: Copy resource PDFs to Google Storage Bucket - Part 5
    deploy:
    - provider: script
      script: bash ./infrastructure/prod-deploy/deploy-resources-5.sh
      skip_cleanup: true
      on:
        branch: master
notifications:
  email: false
  slack:
    rooms: deptfunstuff:abJKvzApk5SKtcEyAgtswXAv
    on_success: change
    on_failure: change
stages:
- name: test
- name: develop deploy
  if: branch = develop
- name: production deploy
  if: branch = master
env:
  global:
    secure: p6CbsBfyGwRjGqb6z0yAtLcXzSXmpW1wwJTgIU8m7aJDxvA6xH6aKSOGoAVWUrFRX492hm6HiVnd0I4EwAOvGtTFB9Ssu25rMMwEgze/4qVASnxPrm4nTMpCIp/MwNzhyTl+DYuQZyt2OuBx2ntSwBgaIkXnS1jbNWOcUeXwJpvmwiGnbIcTXoCiyVPxfjVoE+zG04GOyc96MOdgo+bJKCGHubDwds7bRwpDYR1vkz9C4Qz9R34SEw46HHcGqhp71WvjaCG7aeg8uVF2Kmk8Vv7Ln/Fw7F0sEmRRsPH2kxHeJr7rZhCsTU1JylsSXXKBSP+avXHK1KcXVPzSjlRmg+ZPiAvvtRAL/GuDuJavYnf2XK6HbNHSp+c+km5yTkqafL9KPFavNS0SL8BlL0rk6HJb4k7e1gsZkK0u8u/I30JjNkpKiwDNe4siw84tyLt82k0FDGtcJR2tWSKcVNd+d4gvKT2iMyQO3rxj09Oh//oBBS9AaNgfWzy5gjPzu9Yi6FZQJmJEnVj8kWv9ZzaeLl7ZRdpqyXMTBh7hy8GNgZTGM3NUotM5jvwrTZXF6NBU8NP4zT7GQmUV0rVTSHyVY+9NM7RWSWRi9XdFNcs8cPP03531fMGiZwHkD5weB5NwIECiDJrkmx4c1zfGggpbTKTICWVOBOPzlf8+vaZxSok=
